morocco_housing:
  target: dev

  outputs:
    dev:
      type: duckdb

      path: "{{ env_var('DUCKDB_PATH', '../morocco_housing_ingestion.duckdb') }}"

      extensions:
        - parquet
        - httpfs

      threads: 1